
services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"

  longrunningapp.webapp:
    build:
      context: Host/LongRunningApp.WebApp/
      dockerfile: Dockerfile
    container_name: "LongRunningApp.WebApp"
    image: "longrunningapp.webapp:dev"
    ports:
      - "4200:4200"
    networks:
      - my-network

  longrunningapp.api:
    build:
      dockerfile: Host/LongRunningApp.Api/Dockerfile
    container_name: "LongRunningApp.Api"
    image: "longrunningapp.api:dev"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
  
    ports:
      - "7145:8080"
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
